/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./site.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#a9c7ff",
        "surface-tint": "#005db7",
        "primary-container": "#1565c0",
        "secondary-container": "#e4e2e1",
        outline: "#727783",
        "on-primary-container": "#0d47a1",
        "surface-dim": "#d8dae2",
        "surface-container-high": "#e7e8f0",
        "on-tertiary-container": "#ffdece",
        "surface-variant": "#e1e2ea",
        "surface-container": "#ecedf6",
        "on-secondary-fixed": "#1b1c1c",
        "on-surface": "#191c21",
        "inverse-on-surface": "#eff0f9",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        primary: "#004d99",
        secondary: "#5f5e5e",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3fb",
        "surface-container-highest": "#e1e2ea",
        "on-primary-fixed-variant": "#00468c",
        "on-surface-variant": "#424752",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed": "#e4e2e1",
        "surface-container-lowest": "#ffffff",
        surface: "#f9f9ff",
        "inverse-surface": "#2e3037",
        background: "#f9f9ff",
        "tertiary-container": "#a64c00",
        "on-tertiary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#753400",
        "outline-variant": "#c2c6d4",
        "on-primary-fixed": "#001b3d",
        tertiary: "#813900",
        "on-primary": "#ffffff",
        "on-secondary-container": "#656464",
        "secondary-fixed-dim": "#c8c6c6",
        error: "#b00020",
        "tertiary-fixed": "#ffdbc9",
        "primary-fixed-dim": "#a9c7ff",
        "on-background": "#191c21",
        "tertiary-fixed-dim": "#ffb68c",
        "primary-fixed": "#d6e3ff",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        gutter: "16px",
      },
      fontFamily: {
        notoSansThai: ["Noto Sans Thai", "sans-serif"],
        "label-md": ["Noto Sans Thai"],
        "headline-md": ["Noto Sans Thai"],
        "body-lg": ["Noto Sans Thai"],
        "body-md": ["Noto Sans Thai"],
        "headline-lg-mobile": ["Noto Sans Thai"],
        "label-lg": ["Noto Sans Thai"],
        "headline-lg": ["Noto Sans Thai"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
